counter=0
counter_sampling=[0,5]
channel=0
linkpositions=[]
stream = '' # stream adress
live_signal=0
muteliveposition=0
mutestate =False
begin = 0
fs=0
samples_to_muteramp_analyze=[]
mute_detect_samplingAudio=0
mute_treshold=22
stop_request=0
beg_counter=0
print_counter=5
__mute_ramp_result__=[]
_Time_to_Analyze_=10
server_adress = 0
addr=[]
driver= 0
webdriver = ""
_recordondemand_path_=''
start_time=0